version: '3.8'

services:
  task-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Монтируем папку с базой данных для сохранения данных
      - ./database/prisma/database:/app/database/prisma/database
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./database/prisma/database/task-server.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
